version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    volumes:
      - .:/usr/src/app
    command: ["python", "/usr/local/lib/python3.9/site-packages/debugpy","--listen", "0.0.0.0:5678", "-m", "uvicorn", "radio.main:app",  "--host", "0.0.0.0", "--port", "8000","--reload"]
    ports:
      - 8000:8000
      - 5678:5678
    # env_file:
    #   - .env
    networks:
      - app-network



networks:
  app-network:
    driver: bridge
