
FROM python:3.8-slim as build-deps

WORKDIR /usr/src/app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
# RUN --mount=type=cache,target=/root/.cache pip install --no-cache-dir

FROM python:3.8-slim

WORKDIR /usr/src/app

COPY --from=build-deps /usr/local /usr/local
COPY . .
