[tool.isort]
profile = "black"

[tool.ruff]
[tool.ruff.per-file-ignores]
"__init__.py" = ["E402"]

[tool.pytest.ini_options]
addopts = "-v --import-mode=importlib"
pythonpath = ["src"]
testpaths = [
    "tests"
]