import logging

from fastapi import APIRouter

from src.content_creator.content_creator_instance import content_creator

logger = logging.getLogger(__name__)


router = APIRouter(prefix="/speaker", tags=["speaker"])


@router.get(path="/lines")
def get_speaker_lines():
    """
    Get the speaker lines generated by the first channel's content creator.

    Returns:
        list: The speaker lines generated by the content creator.
    """
    lines = content_creator.channels[0]._generate_speaker_lines()
    return lines


@router.get(path="/react-to-email")
def react_to_email_message():
    """
    Reacts to an email message and returns the lines of the response.
    """
    lines = content_creator.channels[0]._react_to_email_message()
    return lines
