from typing import List

from src.config.music_config import MusicConfig

from .ai_generator import AIGenerator
from .algorithmic_generator import AlgorithmicGenerator
from .custom_generator import CustomGenerator


class MusicGenerator:
    """
    Class representing a music generator that combines AI, algorithmic, and custom generators.

    Args:
        config (MusicConfig): The configuration object containing the settings for the generators.
    """

    def __init__(self, config: MusicConfig):
        self.ai_generators: List[AIGenerator] = []
        for ai_config in config.ai_generators:
            self.ai_generators.append(AIGenerator(ai_config))

        self.algorithmic_generators: List[AlgorithmicGenerator] = []
        for algorithmic_config in config.algorithmic_generators:
            self.algorithmic_generators.append(AlgorithmicGenerator(algorithmic_config))

        self.custom_generators: List[CustomGenerator] = []
        for custom_config in config.custom_generators:
            self.custom_generators.append(CustomGenerator(custom_config))

    def _generate_ai_music(self, n: int):
        """
        Generates AI music using the AI generators.

        Args:
            n (int): The number of music files to generate.
        """
        for generator in self.ai_generators:
            generator.generate(n)

    def _generate_algorithmic_music(self, n: int):
        """
        Generates algorithmic music using the algorithmic generators.

        Args:
            n (int): The number of music files to generate.
        """
        for generator in self.algorithmic_generators:
            generator.generate(n)

    def _generate_custom_music(self, n: int):
        """
        Generates custom music using the custom generators.

        Args:
            n (int): The number of music files to generate.
        """
        for generator in self.custom_generators:
            generator.generate(n)

    def generate_music(self, n: int):
        """
        Generates music using all the available generators.

        Args:
            n (int): The number of music files to generate.
        """
        self._generate_ai_music(n)
        self._generate_algorithmic_music(n)
        self._generate_custom_music(n)

    def get_music(self) -> List[str]:
        """
        Returns a list of music files generated by all the generators.

        Returns:
            List[str]: List of music file paths.
        """
        music_files = []
        for generator in self.ai_generators:
            music_files += generator.get_music()

        for generator in self.algorithmic_generators:
            music_files += generator.get_music()

        for generator in self.custom_generators:
            music_files += generator.get_music()

        return music_files
